# fly.toml file generated for recipe-api on 2023-10-27
#
# See https://fly.io/docs/reference/configuration/ for information about this file.

app = "recipe-api-backend"
primary_region = "scl" # Choose a region close to your users, e.g., "scl" for Santiago, Chile

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["paketo-buildpacks/python"]

[build.args]
  BP_CPYTHON_VERSION = "3.11.4"

[env]
  PORT = "8000" # FastAPI will run on this port
  # Add other environment variables here, e.g., DATABASE_URL, SUPABASE_URL, SUPABASE_KEY, GEMINI_API_KEY, YOUTUBE_API_KEY, SECRET_KEY
  # These should be set as secrets on Fly.io, not directly in fly.toml for production
  # Example:
  # DATABASE_URL = "postgresql://user:password@host:port/database"
  # SUPABASE_URL = "https://your-project-ref.supabase.co"
  # SUPABASE_KEY = "your-supabase-anon-key" # Use anon key for client-side, service_role key for backend
  # GEMINI_API_KEY = "your-gemini-api-key"
  # YOUTUBE_API_KEY = "your-youtube-api-key"
  # SECRET_KEY = "your-super-secret-key"
  # DEBUG = "False"
  # ALLOWED_ORIGINS = "https://your-frontend-domain.com"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 # Scale down to 0 when idle
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

# You can add more sections for volumes, services, etc. as needed.
# For a simple FastAPI app with Supabase, this should be a good start.
