"""Add user recipe model

Revision ID: d9b3e96eb008
Revises: a978ec254aa9
Create Date: 2025-07-13 07:00:58.380362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b3e96eb008'
down_revision: Union[str, Sequence[str], None] = 'a978ec254aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('time_info', sa.JSON(), nullable=True),
    sa.Column('servings', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recipes_id'), 'user_recipes', ['id'], unique=False)
    op.create_index(op.f('ix_user_recipes_title'), 'user_recipes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recipes_title'), table_name='user_recipes')
    op.drop_index(op.f('ix_user_recipes_id'), table_name='user_recipes')
    op.drop_table('user_recipes')
    # ### end Alembic commands ###
